### ISSUE TITLE
Provide __instance structs by-reference

### ISSUE THREAD

**Issue by dymanoid** [pardeike/Harmony#117]
Using version 1.2.0.1.
It seems that the structs are being provided by-value to the prefixes and postfixes which is somewhat useless and also affects performance with large structs (because struct needs to be copied).

Assuming we have:

```csharp
struct Struct
{
    public int Value;
    public void Compute() { Value++; }
}
```

If we patch the `Compute` method with a prefix (or postfix) like that:

```csharp
static void Prefix(ref Struct __instance)
{
    __instance.Value++;
}
```

then this will have no effect on the original `Struct`'s instance. Despite being acquired with `ref`, the patch seems to get a copy of the struct.

Can you confirm this or am I missing something?

**Comment by pardeike** [comment]
Interesting, i will revisit the generation of IL glue code in Harmony. I quickly tested that some prototype code could change the content of the struct when passed via ref.

**Comment by pardeike** [comment]
Fixed in https://github.com/pardeike/Harmony/commit/608a358d761ac75857b178f9f59499ac1c0ee952. Harmony will allow you to pass structs by ref or not (less efficient but if you really want to not use 'ref' then so be it). Also fixed some edge cases with __result and structs.

Please verify, I will close this for now.
