### ISSUE TITLE
Altering return code with postfix

### ISSUE THREAD

**Issue by AnthonyDewhirst** [pardeike/Harmony#130]
Hi,

I am brand new to this, but the project looks like it might suit my needs exactly.
I am replacing Fakes from MS as they require a higher subscription than community to get them.

I first looked at pose, but was struggling with what it was doing. I believe harmony could be the answer.

I am not sure I am looking in the correct place in the wiki, but I don't understand how to get access to variables/return values from the method into the prefix/postfix.

I am also wondering if you can alter the return value with a postfix rather than using a transpiler, which I would like to avoid as learning IL wasn't on my agenda this week! Not that I shouldn't learn it, just would like to if possible. Especially as it eases the learning curve for others in my team.

So, could I have an example that shows changing the return value of DateTime.Now with w different datetime, as this would show off a few of the features I don't quite yet understand.

All help, really really appreciated.

I don't have permission to a label for documentation or help wanted as opposed to an actual issue with the code.

**Comment by AnthonyDewhirst** [comment]
Sorry, been a long few days...
Read the wiki...properly this time.
Piece of cake! 

Great Project!

**Comment by pardeike** [comment]
I just saw you closed it before I could answer. Here is my answer with a few things that are not yet in the wiki for the latest version:

Accessing variable isn’t possible in a prefix or postfix. You can access fields and method arguments. 

Method arguments are matched by type and name so you can simply replicate them in your prefix or postfix. If you add “ref” to the argument (especially in a prefix) you can alter the argument before the original methods gets it. 

Fields can be injected if they are defined in the class of your original method. Use three underscores followed by the exact field name and match the type. Harmony will inject the value for you. Using “ref” to change values is possible too. 

To get the the current instance of a method (non-static) you use two underscores followed by “instance” with the type of the class. Harmony will inject the instance for you.

Another special argument is the __result (two underscores again). It can be used in the postfix to read the result of the original. With “ref” it can be changed in both, the prefix or the postfix. 

All this works for the arguments of the prefix or the postfix methods you define. The prefix can have a bool result which controls the execution of the original (true = execute).  

Finally, the postfix has a “pass through” mode where you have it return the same type as it’s first argument. Name of that argument is free to choose. Harmony will send in the original result into the first argument and you are suppose to return the final version of it from your postfix. That is very useful for IEnumerable<> result types because you can iterate on the argument and yield return values to your liking. 

Transpilers are mostly used to exchange method calls inside a method with methods you define yourself and that execute your extra logic. You can do much more but that requires explicit knowledge of CIL. I usually exchange a method with Transpilers.MethodReplacer() and maybe add some extra elements/localvars before the call onto the stack to have all I need in my replacement method where I then call the original method. 

Regarding patching DateTime.Now: Make sure of the pitfalls of patching standard lib functionality. Some of those methods are inlined or mapped to native executions or are plain weird in their call stack. Which means that Harmony has a hard time patching them. But it really depends on the method you patch. 

Hope this helps a bit
Andreas Pardeike

**Comment by AnthonyDewhirst** [comment]
Great feedback. Thanks for responding so quick.
It was the bit of the wiki about the params my eyes had completely skipped the first time.
The DateTime.Now seems to work, but the DateTime.UtcNow seems to hang the running of the code.
As I said, it was to have a test that mocked out standard lib code, and it works for what I want. I wonder if other people would be interested in using Harmony for this?

My first stab of code looks like the following (written in 10 minutes at 11pm so please excuse its quality!)


the Test
``` c#
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void ReplaceDateTimeNow()
        {
            Harmony.Isolate(instance =>
            {
                // Arrange
                instance.ReplaceStaticGetter(() => DateTime.Now, new DateTime(2000, 2, 3));

                // Act
                var actual = DateTime.Now;

                // Assert
                Assert.AreEqual(new DateTime(2000, 2, 3), actual);
            });
        }
    }
```

The wrapper to ensure patches revoked
```c#
    public class Harmony
    {
        public static void Isolate(Action<HarmonyInstance> test)
        {
            var instance = HarmonyInstance.Create("testing");

            try
            {
                test(instance);
            }
            finally
            {
                instance.UnpatchAll();
            }
        }
    }
```

The property replacement. I used a generic class so that I could use static variables and have simple class generation. Would really like to replace this with in memory class, that can handle Actions and Functions
```c#
   public class PropertyShim<TClass, TProperty>
    {
        public static TProperty Property;

        public static TProperty Get(TProperty originalResult)
        {
            return Property;
        }
    }
```

And the actual Patch/Shim implementation (very rough)
```c#
    public static class HarmonyExtensions
    {
        public static void ReplaceStaticGetter<T>(this HarmonyInstance instance, Expression<Func<T>> expression, T value)
        {
            if (expression == null)
            {
                throw new ArgumentNullException(nameof(expression));
            }

            MemberInfo getter = null;

            if (expression.Body is MemberExpression memberExpression)
            {
                // Reference type property or field
                getter = memberExpression.Member;
            }

            if (expression.Body is MethodCallExpression methodCallExpression)
            {
                // Reference type method
                getter = methodCallExpression.Method;
            }

            if (expression.Body is UnaryExpression unaryExpression)
            {
                // Property, field of method returning value type
                getter =  GetMemberInfo(unaryExpression);
            }

            if (getter == null)
            {
                throw new ArgumentException("The expression is not a property");
            }

            var classType = getter.DeclaringType;
            var getterName = getter.Name;

            var getterMethod = classType.GetMethod($"get_{getterName}");

            if (getterMethod == null)
            {
                throw new ArgumentException($"Can't find the getter method for the property {getterName}");
            }


            var shimType = typeof(PropertyShim<,>).MakeGenericType(classType, typeof(T));

            var shim = Activator.CreateInstance(shimType);
            shimType.GetField("Property").SetValue(shim, value);

            var postfix = shimType.GetMethod("Get");
            instance.Patch(getterMethod, postfix: new HarmonyMethod(postfix));
        }

        private static MemberInfo GetMemberInfo(UnaryExpression unaryExpression)
        {
            if (unaryExpression.Operand is MethodCallExpression)
            {
                var methodExpression = (MethodCallExpression)unaryExpression.Operand;
                return methodExpression.Method;
            }

            return ((MemberExpression)unaryExpression.Operand).Member;
        }
    }
```

Any feed back would be great!
