### ISSUE TITLE
Patching "const return" method doesn't apply

### ISSUE THREAD

**Issue by MiincK** [pardeike/Harmony#149]
Trying to patch some methods when "Optimize code" enabled when building project you are patching

When I am trying to patch a method that looks like this:
```csharp
		static int ToPatch()
		{
			return 2;
		}
```
Harmony patches it successfully, but a patch don't get executed. I tried the transpiler like this:
```csharp
		static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instr)
		{
			return new List<CodeInstruction>
			{
				new CodeInstruction(OpCodes.Ldc_I4_5),
				new CodeInstruction(OpCodes.Ret)
			};
		}
```
And also a prefix like this:
```csharp
		static bool Prefix(ref int __result)
		{
			__result = 5;
			return false;
		}
```
And even a postfix like this:
```csharp
		static void Postfix(ref int __result)
		{
			__result = 5;
		}
```
That methods are applied successfully, but doesn't execute. I always get `2` after patch when I execute the target method.
Also I have noticed one thing: when I run the executable from dnSpy with debugging, patch WORKS. Method returns `5` instead of `2`.
Easiest way to reproduce that is making a simple patch executable and running it with "Debug" build in VS (patch works), and with "Release" (patch DOESN'T work)

OS: Win10x64
Harmony: latest 1.2.0.1
Visual Studio 2017 Community

**Comment by pardeike** [comment]
Methods like the one you mentioned are often inlined by the JITer during runtime generation of assembler code from the C#/IL code. Since the methods assembler code will become part of the code of the calling method, there is no way to patch them during runtime (only by editing the dll).

**Comment by MiincK** [comment]
Hm, so why when I run program from dnSpy id doesn't inline? Is there any environment vars or something that prevents JIT from inlining this? Can I so something for JIT not inlining methods in newly loaded assemblies on runtime?

**Comment by pardeike** [comment]
I think there are some startup parameters to prevent inlining but it would prevent inlining everywhere which is considerable slower.

There is no documented way to prevent inlining during runtime. See also

https://stackoverflow.com/questions/3329214/is-it-possible-to-force-a-function-not-to-be-inlined

https://manpages.debian.org/testing/mono-runtime-common/mono.1.en.html

https://stackoverflow.com/questions/5169219/preventing-jit-inlining-on-a-method

The problem is that this is not well documented and also different for different .NET versions and runtime environments.

**Comment by pardeike** [comment]
If you find a way to prevent inlining in mono, please let me know.
