### ISSUE TITLE
Patching with an instance method, or retaining patch context

### ISSUE THREAD

**Issue by phxvyper** [pardeike/Harmony#199]
Is there a way to inform Harmony of state information that I want to be passed to a prefix method when it is called, on a per-patch basis?

This is an example of what I tried, prior to learning that patch methods have to be static:
```cs
class Binder<TOn>
{
    // ...
    private Model _model = ...;

    private void Install()
    {
        MethodInfo toMethod = ...;
        MethodInfo onMethod = ...;
        // ...

        Action<TOn> onSetter = (value) => toMethod?.Invoke(_model, new object[] { value });
        _harmony.Patch(onMethod, new HarmonyMethod(onSetter.Method));

        // ...
    }
}
```
`onMethod` and `toMethod` are both MethodInfos for setters for a property in an instance of a type. Of course, this did not work, because `onSetter` is local and has local state/is not static.

Is there a way to retain references to `toMethod` and `_model` on *this specific patch*, even if I refactor `onSetter` into a static method? If I run this patch on different `onMethod`'s, I would want each one's new prefix to be called with its own state.

**Comment by pardeike** [comment]
The main problem here is that Harmony replays all patches whenever some other mod patches the same method.

After adding patch1 + patch2:
Original (from IL code) -> patch1 -> patch2 -> ... -> Current

After removing patch2:
Original (from IL code) -> patch2 -> ... -> Current

This means that "your" state needs to be available when another mod wants to patch the method. And since this is across assembly borders, everything needs to be serialized because asm1.TypeA != asm2.TypeA - even if they are the same they are not assignable.

That is the main reason on why patches are static.

**Comment by pardeike** [comment]
The only way to add state to patches is thus to give them each a value key (int, or string) and embed it in the IL code as a constant. That could then be used to pull information from a central state repository.
