### ISSUE TITLE
Discussion on a new field injection feature

### ISSUE THREAD

**Issue by pardeike** [pardeike/Harmony#20]
Hi,

I am thinking of adding more argument injections to patch methods. Currently, we have
- original method arguments (by exact name and type)
- **__instance** to get to *this* for non-static methods
- **__state** to create a local variable holding state between prefix and postfix
- **__result** to access the original methods result value

What often happens is that you want to access private fields of the original methods class but it adds a lot of overhead in form of performance and code to your patch methods.

So my proposal is that you can add arguments to the patch methods that match the type and name of a field and Harmony will inject those for you.

Example:

```csharp
class Foo
{
	private List<String> aList;
	
	private void SomeMethod(String foo)
	{
		aList.Add(foo);
		// ...
	}
}
```

could be patched with

```csharp
[HarmonyPatch(typeof(Foo))]
[HarmonyPatch("SomeMethod")]
static class FooPatch
{
	static void Prefix(ref String foo, List<String> aList)
	{
		// ...
	}
}
```

Some reflections:

- Naming could be an issue. I don't want to overcomplicate things with a required name prefix and I assume giving the original method argument names that are the same as its fields will cause conflicts anyway, or are there edge cases?
- Are there other cases of injections that are useful?

Anyone care to discuss this?

**Comment by DoctorVanGogh** [comment]
Stupid idea time :grin:

## Get rid of the hardcoded parameter names (keep it as base case, but offer an indirection layer):
```csharp
enum SpecialParam {
  Result,
  Instance,
  State,
}

[AttributeTarget(AttributeTargets.Parameter, AllowMultiple=false)]
class ParamAttribute : Attribute {
  ParamAttribute (SpecialParam type) {
    ...
  }
  ParamAttribute (string parameterName) {
    ...
  }
}
[AttributeTarget(AttributeTargets.Parameter, AllowMultiple=false)]
class FieldAttribute : Attribute {
  FieldAttribute (string fieldName) {
...
 }
}

```
Then consumers could simply declare

```csharp
[HarmonyPatch(typeof(Foo), nameof(Foo.Thingy)]
class Foo_ThingyPatch {
    static void Postfix(
        [Param(SpecialParam.Result)] List<Bar> parameterExplicitlyNotNamedAnythingLikeResult, 
        [Param(SpecialParam.Instance)] Foo foo,
        [Param("methodParam1")] int p1,
        [Field("privateFieldXYZ")] Baz xyz
    ) {
    }
}

```
I'd strongly suggest keeping the attribute names as short as possible, otherwise attributing the patches becomes longer than those special names again.
For unattributed parameters fall back to the current 'special' names.

That way you'd 
- Simplify current uses (No more magic names)
- Be able to offer field access
- Avoid all the naming collisions you could imagine
- Have an extensibility mechanism for future additional mappings - just write more attributes

_Maybe_ you could be nice and offer some sort of `Func<T> GetFieldGetter<T>(FieldInfo fi)` & `Action<T> GetFieldSetter<T>(FieldInfo fi)` methods (possibly with easier parameters, but they'd all reduce to this) since you'll have to implement 95% of the work anyway.

**Comment by DoctorVanGogh** [comment]
Addendum: 
Found another injection case

### Injected properties
```csharp
[AttributeTarget(AttributeTargets.Parameter, AllowMultiple=false)]
class PropAttribute : Attribute {
  PropAttribute (string propertyName) {
...
  }
```
If you want to offer (private) field mapping, you might as well offer (private) property mapping.

**Comment by pardeike** [comment]
Ok, I had this idea before but I was put back by the ugly code. I just hate inline annotations but I guess there is no easy way around this. The only way I can think of to make this more "nice" is to have the annotations on the method itself but you loose the coupling which is not acceptable.

Another thing to consider: why stop at private fields and properties. What I really want is property paths! If you have

```csharp
private class PrivClass1
{
	private String secret;
}

private class PrivClass2
{
	private PrivClass1 Foo { get { return new PrivClass(); } }
}

private static PrivClass2 bar = ...
```

I would love to inject with

```csharp
[HarmonyPatch(typeof(Foo), nameof(Foo.Thingy)]
class Foo_ThingyPatch {
    static void Postfix(
	[DotPath("bar.Foo.secret")] String theSecret
    ) {
    }
}
```

**Comment by DoctorVanGogh** [comment]
### "Dot-mappings"

Yikes.... Are you sure you want to do that? 

If you start down that road, which access expressions will you support? What about `bar.Foos[17].secret` or even `bar.Foos.Avg(f => f.Shinyness)`?
Ultimately your mapping will just become a thin facade on top of C#.

_If_ this was running under .NET 4 you could push a lot of the work onto library consumers by expceting expressions, but the 3.5 expression support is somewhat limited. But then again, consumer could only reference public members...

I'd vote for just offering Field & Property mappings as well as General on-demand restricted member access creators:

```csharp
class Foo {
  private Bar _bar;
  private static Baz Baz;
  
  private static void Magic(int p, Foo f, string s) {... }
}

// something like
Func<Foo, Bar> barGetter = Harmony.GetGetter<Foo, Bar>("_bar");
Action<Foo, Bar> barSetter = Harmony.GetSetter<Foo, Bar>("_bar");

// or even
class Accessor<T, M> {
  public M Get(T instance) {...} 
  public void Set(T instance, M value) {...} 
}
class Accessor<M> {
  public M Get() {...} 
  public void Set(M value) {...} 
}
...
// should work for both fields & properties
Accessor<Foo, Bar> barAccessor = Harmony.GetAccessor<Foo, Bar>("_bar");
Bar value = barAccessor.Get(foo);
barAccessor.Set(foo, new Bar());
Accessor<Baz> bazAccessor = Harmony.GetAccessor<Bar>(typeof(Foo), "Baz");
Baz value = bazAccessor.Get();
bazAccessor.Set(new Baz ());
```
And if you want to add accessors for private methods (to complete all restricted `MemberInfo` variants) add support for
```csharp
delegate void MyCustomMethodHandler(int p, Foo f, string s);

MyCustomMethodHandler fnMagic Harmony.GetMethod<Foo, MyCustomMethodHandler>("Magic");
fnMagic(42, new Foo(), "Waffles!");
```
Though if you want to define that correctly (like `TDelegate GetMethod<T, TDelegate>(string name) : where TDelegate : Delegate {... }` you'll have to think about assembly weavers like [Fody](https://github.com/Fody/Fody) & [ExtraConstraints](https://github.com/Fody/ExtraConstraints) for the harmony project (though both are plain nuget packages, so are utterly easy to install)

---
If consumers could just get their accessors to whatever they need, they could mix and compose those to arbitrary depths & complexities. No need for you to special case a limited subset like `xyz.abc.def`.

### Side-effects, value setters & `ref` parameters

On a completely (un)related topic
You cannot declare properties as `ref` parameters (with good reason). You get compiler error [CS0206](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0206). Using VB.NET kinda works around this, but it's still unusable.

The Question is: When does the ref parameter value get written back to the underlying source? 
- On Access? Then things should be okay. 
- On method return? That might be too late. Property setters might (and typically have) side effects, like notifications or cascade updates. Subsequent calls to other code (before method return) might work on inconsistent or unexpected object states.

So it would probably be better to directly map properties to Get-/Set Accessor tuples instead of a "simple" value parameter.
Again - if you offer arbitrary restricted member accessor helpers this comes out-of-the-box

**Comment by pardeike** [comment]
The latest additions in v1.2.0 are making this obsolete. Closed for now.

**Comment by AnnanFay** [comment]
Was this ever revisited?

I'm new to the library and unsure what changes v1.2.0 had on this suggestion. Did v1.2.0 implement something like this?

**Comment by pardeike** [comment]
Fields are injected by prefixing their names with triple underscores. This allows for private field access in the original methods class. For anything else, AccessTools also has FieldRef which is a super cool way to use private fields
