### ISSUE TITLE
Incorrect documentation of Patching/Prepare

### ISSUE THREAD

**Issue by DJPop** [pardeike/Harmony#202]
According to the [wiki](https://github.com/pardeike/Harmony/wiki/Patching)

> Prepare (Optional)
> 
> Before the patching, Harmony gives you a chance to prepare your state. For this, Harmony searches for a method called
> 
> static bool Prepare()
> static bool Prepare(MethodBase original)
> // or
> [HarmonyPrepare]
> static bool MyInitializer(...)
> 
> That method, if it exists, is expected to return a boolean that controls if patching will happen. You can optionally receive the original method.

Parameter of **static bool Prepare(MethodBase original)** is incorrect.
The first parameter, if provided, will always be **HarmonyInstance**.
These 3 methods are valid.

> static bool Prepare()
> static bool Prepare(HarmonyInstance instance)
> static bool Prepare(HarmonyInstance instance, MethodBase originalMethod)

**Comment by pardeike** [comment]
That depends. Harmony 1.2 and the upcoming Harmony 2.0b differ in that 2.0 will accept arguments in any order and have them optional too. If I had time to maintain two versions of the documentation, I would. For now, the documentation website should match 2.0 and the wiki should match 1.2

**Comment by ewwink** [comment]
I just got an error migrating from `.dll` to this repo, found that it changes from

```
var harmony = HarmonyInstance.Create("com.id");
```

to

```
var harmony =  new Harmony("com.id");
```

**Comment by pardeike** [comment]
Wiki is for 1.2, https://harmony.pardeike.net is for 2.0b (which is not official yet).

**Comment by lbmaian** [comment]
Can you also update the v1.2 wiki (https://github.com/pardeike/Harmony/wiki/Patching) to state that the `[HarmonyPrepare]` attribute doesn't work in this version due to #193?

It should say something like:

---------------

**Prepare** (Optional)

Before the patching, Harmony gives you a chance to prepare your state. For this, Harmony searches for a method called

```csharp
static bool Prepare()
static bool Prepare(HarmonyInstance instance)
static bool Prepare(HarmonyInstance instance, MethodBase original)
// or
// NOTE: this is broken in 1.2.0.1
[HarmonyPrepare]
static bool MyInitializer(...)
```

That method, if it exists, is expected to return a boolean that controls if patching will happen. You can optionally receive the harmony instance and the original method.

**Comment by pardeike** [comment]
I choose to not update the 1.2 Wiki and instead put my effort and focus in 2.0. So this is a WONTFIX for now.
