### ISSUE TITLE
Question: Harmony in Enterprise projects

### ISSUE THREAD

**Issue by alexb5dh** [pardeike/Harmony#209]
From what I saw Harmony is mainly used in gaming mods and not often in other areas. But it's ability to extend or modify nearly any code, including BCL is really useful and can be helpful in any project.

For example, this allows to easily update an external NuGet package without waiting for new release or PR to be merged. Or even tweak the base framework to better fit current project needs.

So I'm wondering if it's safe to use it in enterprise projects like ones built on ASP.NET or WPF. Are there any known vulnerabilities that prevent Harmony to be used in commercial projects? Or is it just not very popular in this field?

**Comment by pardeike** [comment]
The reason is that it’s used with games a lot. I did have feedback from some Microsoft engineer that it caused quite some discussions internally and it seems to fit some enterprise areas. I work in government enterprise and I would deem Harmony “fit but with some reservations”. It will not work in areas with strict memory access rights like in managed web containers (or at least it’s undocumented where it works exactly). It is also dependent on the .NET version and the ability to generate dynamic code at runtime which some environments won’t allow or a security department might not approve. 

But there are no general reservations against using Harmony in enterprise. It’s open source so I strongly suggest cloning it into an independent internal repository but that’s good practice with everything you depend on.
