### ISSUE TITLE
Question: void prefix() - how exactly it works?

### ISSUE THREAD

**Issue by krypt-lynx** [pardeike/Harmony#236]
I'm poking a third party library which uses Harmony
It has usage I never seen before (in code or in documentation):
https://github.com/jecrell/JecsTools/blob/master/Source/AllModdingComponents/CompActivatableEffect/HarmonyCompActivatableEffect.cs#L263

This prefix has no return value.
Will original method be called in this case?

**Edit:** It is a postfix actually, despite being named prefix

**Comment by krypt-lynx** [comment]
Also, original method uses `yield return`
How exactly it should be patched? This method already does not works as intended, looks like.

**Comment by pardeike** [comment]
In general, if you see `ref T __result` then a Prefix/Postfix **is** modifying the originals result. That's documented on the Harmony Wiki. A prefix can only have void/bool return types and the boolean determines if the original is executed or not. A postfix can only have void as a return type with the exception of a "passthrough postfix". Such a postfix is defined by having the same return type as the first argument and is then used to as a filter in which the original result is fed into the first argument and that then returns the possibly modified result. That has the benefit that it works with types that cannot be ref'ed or with Enumerations. In the later case, you can read from the input and yield to the output which gives you a lot of ways to patch an Enumeration method.

Enumeration methods are not real methods. They contain only a very small part that instantiates a hidden compiler generated class that acts as a state machine with one giant MoveNext() method that contains a large switch statement for every yield. So you cannot patch them with normal Prefix/Postfixes. You either need to find the hidden class and the MoveNext method and transpile it or you can use a passthrough postfix.

With all that said, I am pretty sure the code you linked does not work correctly.

**Comment by krypt-lynx** [comment]
> "passthrough postfix"
`static IEnumerable<TExample> Postfix(IEnumerable<TExample> __result)`
or? I should to __result.concat? you I can do `yield return`?

> as the first argument
Why the first?
I can write `static int Postfix(int arg0, IEnumerable<TExample> __result)`?
What exactly it will do? Does it even have a sense?

**Comment by krypt-lynx** [comment]
Hm. Is I really that unobservant or documentation actually does not linked anywhere on in this repo?
https://harmony.pardeike.net/#documentation

**Comment by pardeike** [comment]
A simple passthrough postfix:

```cs
static IEnumerable<Int> Postfix(IEnumerable<Int> somename, .....alll the normal postfix arguments)
{
   //...
   yield return 123;
   //...
}
```

**Comment by pardeike** [comment]
The documentation is linked from the main repo page.

**Comment by krypt-lynx** [comment]
I mean, link to your site. I see only github wiki urls on repo's main page.
But I still have a question: how exactly I should filter what IEnumerable<Int> if I will decide to do it?

**Comment by pardeike** [comment]
That's exactly the reason I don't document the passthrough postfix. Most people don't understand generator functions (those with yield's) and I am tired of explaining things that have nothing to do with Harmony to them.

Super short. In the following, OriginalMethod is a generator function:

Before patching:
SomeMethod -> OriginalMethod

After patching with passthrough postfix:
SomeMethod -> Postfix -> OriginalMethod

A generator function does not RUN like a normal method. It only runs when some caller wants something from it. So OriginalMethod does not run (that is, run from start to 1st yield or 1st yield to 2nd yield etc) unless SomeMethod wants another value.

With a passthrough postfix, the chain just gets one element larger. SomeMethod asks for an item, Postfix runs to deliver it. Postfix needs an item to do so, asks OriginalMethod and it gets an item. You can then skip or edit that item or return new items that OriginalMethod never returned. You then return (by yielding) in the Postfix. That gets delivered to SomeMethod.

It's PULL instead of PUSH as a general principle. Now that you know that you can design your Postfix. But if you don't want the OriginalMethod to calculate any items at all (not even for replacing them in your Postfix) then you are out of luck and I suggest you learn how to do CIL and a transpiler and you need to use dnSpy or any other disassembler to actually look at the IL level with all compiler generated methods and classes that you normally don't see. It's QUITE COMPLICATED at that level and I recommend the transpiler tutorial that is linked from the main repo page.

> I mean, link to your site. I see only github wiki urls on repo's main page.
Not sure what you mean with "your site".

**Comment by krypt-lynx** [comment]
> Not sure what you mean with "your site".
pardeike.net?

Well, I'm is aware (or I think I'm is aware :D ) How enumerators work, well but does not know hidden details of `yield return` implementation (I'm a developer, but not a .Net/C# developer) (what I seen in dnSpy looks like a same code generated twice, original method and Iterator, maybe dnSpy is not displaying it correctly) 

I'm just trying to understend how exactly Postfix and OriginalMethod are glued together.

Is there some runtime magic and `yield return`inside postfix will add an item into existing IEnumerator?

Or it is literally an `OriginalMethod(<..>).Postfix(<..>)` equivalent?

**Comment by krypt-lynx** [comment]
Well, nothing I can't test by myself, actually

**Comment by pardeike** [comment]
It’s really just like 
```cs
var result = Postfix(Original())
```

so the simplest way to familiarise yourself with the topic would be to use an interactive C# environment and test a few things:

https://gist.github.com/pardeike/9f68fd3f05a04c2081c1b506a0ff9796

**Comment by krypt-lynx** [comment]
Thanks, this answers my questions
