### ISSUE TITLE
Pre/Postfix on properties makes Rimworld crash on Linux

### ISSUE THREAD

**Issue by dhultgren** [pardeike/Harmony#343]
**Describe the bug**
Adding Prefix/Postfix to properties causes Rimworld to crash immediately when that code would be called. Transpiling the same property works fine. This is a verbose log from it happening: https://pastebin.com/58JDUE33

**To Reproduce**
The following code triggers the error, and the result is the same if manual patching is used:
```
[HarmonyPatch(typeof(WorkGiver_Scanner))]
[HarmonyPatch("Prioritized", MethodType.Getter)]
public class PatchClass
{
    public static bool Prefix(WorkGiver_Scanner __instance, ref bool __result)
    {
        // implementation that won't be reached
    }
}
```
**Runtime environment (please complete the following information):**
 - OS: Ubuntu 20.04, but also reported on PopOS 20.04 and multiple unknown distributions
 - .NET version: .NET Framework 4.7.2
 - Harmony version: 2.0.2
 - Game: RimWorld

**Comment by pardeike** [comment]
The problem is known and there is currently no solution for it. Under linux, very short methods generate very short assembler code. Harmony overwrites the start of the assembler with a long jump instruction that jumps to the replacement. Here, the code block is so short that the jump instruction will clobber over the end of it into the next methods code.

Writing a short jump would help but there is no easy way to allocate memory close to that location.

**Comment by pardeike** [comment]
For reference, here is the IL code:
```
.property instance bool Prioritized()
{
	.get instance bool RimWorld.WorkGiver_Scanner::get_Prioritized()
}

.method public hidebysig specialname newslot virtual 
	instance bool get_Prioritized () cil managed 
{
	.maxstack 8

	IL_0000: ldc.i4.0
	IL_0001: ret
} // end of method WorkGiver_Scanner::get_Prioritized
```

**Comment by lbmaian** [comment]
Prior discussion with Zetrith and potential solution around the Linux x64 crash bug: https://discordapp.com/channels/131466550938042369/674571535570305060/732548179807174707

Ideally would be done in MMC itself rather than in Harmony.

In the meantime, @dhultgren have you tried using this workaround mod? https://steamcommunity.com/sharedfiles/filedetails/?id=2149016328

**Comment by dhultgren** [comment]
Right, I understand. Hopefully you can find a way around it or at least detect that you would overwrite other code and log an error instead. It would be a bit more user friendly than practically doing a buffer overflow attack.

@lbmaian I tried but it didn't work. I used a transpiler instead and it works fine, but a postfix would of course be better for compatibility.
