### ISSUE TITLE
Request: Special MethodBase parameter (like __state or __instance) for Prefix/Postfix patches

### ISSUE THREAD

**Issue by Trojaner25** [pardeike/Harmony#36]
I want to apply the same patch for multiple methods which have the same signature, but still want to do different actions depending on the method which got patched. 

Currently I would have to  make Prefix/Suffixes methods for each method which will get patched, to be able to figure out which method I'm currently patching / detouring

**Comment by rumkex** [comment]
Might be even better to allow passing some sort of arbitrary context object to provide a global state between calls to detour methods (like __state parameter allows preserving context inside a single method call, that new global state object will persist between calls and will be created together with the patch), what do you think?

**Comment by Trojaner25** [comment]
I'm trying to do some profiler which starts a Stopwatch on the prefix and stops given Stopwatch on the postfix. It has only a __instance and a __state (__state = StopWatch). But currently I can not use the same Prefix/Postfix for all methods, because I can not get the current patched method.

**Comment by pardeike** [comment]
This conflicts with multiple assemblies patching the same method. Harmony must work across assembly boundaries and in order to have cumulative patches it serializes and deserializes patches to rebuild the final replacement method from all existing patches every time someone adds a new patch to the original. 

So holding state for one particular original method consistently seems kind of hard and would require serialization of the data structures. It might even be that someone patches after you and thus your patch becomes part of their assembly and cannot handle its own types anymore since TypeA is not assignable from TypeA if they are from different assemblies. 

My best guess would be to have the unchanging MethodBase from the original method as an injection parameter and you would need to have your own way to look up that in your own state. It could be called “MethodBase __original”.

**Comment by Trojaner25** [comment]
I have already tried to add such a parameter, but it seems like its a bit tricky

**Comment by pardeike** [comment]
A simple option would be to use the already provided Transpiler patch function. It can have the original method parameter as a parameter. It also has the advantage that you will get less overhead because you can implement your measurements without subroutine calls and that might save you some execution time too (depending on how time critical your patched methods are).

**Comment by pardeike** [comment]
Latest master has support for `MethodBase __originalMethod`

**Comment by Trojaner25** [comment]
Thank you!
