### ISSUE TITLE
Add .net 4.7.1 target framework for Unity LTS support

### ISSUE THREAD

**Issue by Ipsquiggle** [pardeike/Harmony#406]
Presently, both Unity 2019 LTS and 2020 LTS target .net 4.7.1 in their auto-generated projects.

If net471 is added as a TargetFramework and part of the Harmony release package, it would give drop-in support for linking Harmony directly into Unity projects.

(For context, this is because we include 0Harmony.dll in the release of Oxygen Not Included for our mod community, so having a version that's targeted the same as the game simplifies updating for us.)

Let me know if you need more detail! :) Thanks

**Comment by pardeike** [comment]
Sorry, but I am confused. Harmony (via nuget) supports net472 and to my knowledge it’s a dependency one should not include in a library. Like in RimWorld, we all use the net472 that is part of the Unity mono runtime. 

Or am I missing something here?

**Comment by Ipsquiggle** [comment]
I'll admit, I find dealing with .net versions extremely confusing, so I apologize if this seems trivial.

First off, the problem we were running into is only present in Visual Studio 2017, not 2019. This may be much less of an issue than I had originally believed.

Nonetheless, here's what I'm seeing:
 1. We include Harmony right in the Unity project for Oxygen Not Included (the actual game, not a mod).
 2. Unity regenerates .csproj files every time a .cs file is added or removed
 3. Those .csproj files target 4.7.1 upon regenerating.
 4. In VS2017, the project can no longer compile with a referenced 0Harmony.dll@4.7.2 (because 4.7.2 does not match 4.7.1)
 5. In VS2019, the project compiles just fine.

How exactly did you determine that Unity has 4.7.2? Examining both the library folders in my Unity install, I only see up to 4.7.1. Making a build of the game produces DLLs that target framework 4.0.

Honestly if you don't want to fuss with this, we can close this bug. I just feel like every bit of information I get in this puzzle makes it _less_ clear. :)

Thanks for the rapid response in any case!

**Comment by pardeike** [comment]
Hmm, AFAIK, you can simply add a dll to your assets. In this case it shouldn't matter if the project is for 4.7.1 or 4.7.2 since the difference is minimal. Since you are not adding .cs files (which I don't recommend anyway) this should be much simpler than trying to compile Harmony.

I could be wrong but RimWorld uses Unity 2019.2.17 and its Assembly-CSharp.dll is dependent on mscorlib 4.0.0.0. I think one has to differenciate between runtime and compiler features in new versions. Just like .net 2.0, 3.0 and 3.5 are all API compatible and run under 2.0 so will 4.x

I recently wanted to add a bezier path asset to rimworld from a mod. Generating asset bundles and loading them from a mod works fine but source code files can't go into asset bundles. So I took the code of the bezier path asset and compiled my own dll and imported it into the assets of a dummy project, then exported it together with all the other files as an asset bundle. I think the same should work with bundling Harmony dll with the project and since its an ordinary dependency, the exact version should not matter.

I could be wrong though, sometimes the mystery of linking, especially with Unity, is beyond my understanding.

**Comment by pardeike** [comment]
But if it turns out that a 4.7.1 release would solve all this, I can think about adding it. Testing 4.7.1 and 4.7.2 on Azure will increase the test time, so I rather avoid it if possible.

**Comment by Ipsquiggle** [comment]
At the end of the day I decided that making a 4.7.1 build on our end is simple enough, it takes probably just over a minute all-in. Adding it would save us that minute, haha, but it's really not a big deal.

I think at the beginning of this thread I was in a tizzy because of trying to understand how all this versioning stuff works, but now that I've got a handle on it (I think, hahah), I just don't think it's a big issue to make our own 4.7.1 build.

Thanks!

**Comment by jakcharlton** [comment]
Hey quick Q ... I am trying to use a Unity package called FastScriptReload - which has a dependency on 4.8 

This means it shows red errors in VSCode - but still builds and works

I cannot find any way to stop VSCode/Roslyn/Omnisharp from showing errors - and this is driving me buts (I hate seeing red alerts)

@ipsquiggle did you end up just downloading this project and building to a 4.7.1 DLL ? Did this resolve the issue?

**Comment by ipsquiggle** [comment]
@jakcharlton That's correct, we just built the Harmony .dll for 4.7.1 on our end.
