### ISSUE TITLE
Patching multiple variants of a generic method causes the patches to override eachother

### ISSUE THREAD

**Issue by Aidanamite** [pardeike/Harmony#426]
I'm using multiple harmony patches on a single generic method, each patch targets a different "type" of the method. The issue is that which ever one of the patches is applied last overwrites all the other patches of the method.

I have my harmony instance stored in the variable `harmony` and I'm using the following line to add each patch:
```
            harmony.Patch(typeof(ItemDatabase).GetMethod("LoadFromBundle").MakeGenericMethod(type), new HarmonyMethod(typeof(Main).GetMethod("GetAssetPatch",BindingFlags.NonPublic | BindingFlags.Static).MakeGenericMethod(type)));
```

I've tried re-arranging the order that the types are patched in (hence why I know it is the last applied patch that overwrites) and I've tried only patching methods with no overlapping derived or inherited types.

Is there any way to get around/fix this issue? I have thought about creating a new harmony instance for every one of these patches but I think that's a bit excessive and I don't know if that would even change anything.

EDIT: Just tried using a new harmony instance for each patch. did not work

**Comment by pardeike** [comment]
See https://harmony.pardeike.net/articles/patching-edgecases.html#generics

**Comment by pardeike** [comment]
It is unclear and possibly undefined what happens when you patch generic methods. The only way I know to patch a method is by writing an assembler jump at the start of the assembler code that represents the method after the JIT has created the assembler. If the JIT creates extra code that is a standin for the generic method and “does stuff” to either call the methods assembler with some extra type info or instead decides to create and call different implementations for each type is completely opaque and undocumented. Which means you have to deal with the way it is or not patch it at all. AFAIK this is as good as it gets unless I go and reverse engineer all the C/C++ code of decades of .NET runtime code on different platforms and operating systems which probably would take me months and years of my life.
