### ISSUE TITLE
Request: Type level functionality

### ISSUE THREAD

**Issue by FrodoOf9Fingers** [pardeike/Harmony#45]
This may be a special interest request, but...

It'd be nice to be able to annotate an entire type, and then have all of the pre-patches/post-patches apply to every function (maybe allow excluding the constructor). Naturally, these patches would be highly limited in what variables they have access to, but it'd reduce a lot of the boilerplate code I'm using to place objects under concurrency wrappers.

**Comment by pardeike** [comment]
Interesting idea. As you said, a bit of a special case and I doubt how useful it would be for the average user. Also, don't forget that in order to allow multiple Harmony instances to patch the same methods, the shared state needs to be safe to serialize over assembly boundaries. Currently, I only refer to static patch methods as MethodBase is easily transferable. Once you get into other stateful matters it becomes tricky to implement.

But you're welcome to suggest a design that would work. Maybe a patch method that only gets (a possible null) `object __instance` and a `MethodBase __originalMethod` variable? Maybe even what some other Issue here lifted: a generic `object[] __arguments` like this:

```csharp
[HarmonyPatch(typeof(SomeClass))]
[HarmonyPatchAll]
static class MyPatches
{
	static bool Prefix(object __instance, MethodBase __originalMethod, object[] __arguments)
	{
		// code
		return false;
	}
}
```

What do you think?

**Comment by FrodoOf9Fingers** [comment]
That's basically what I was thinking. Around Monday-Tuesday I'll have some time, I'll check out your code for annotating and see if I can make a pull request to match that interface (including postfix, but certainly not transpiler).

**Comment by FrodoOf9Fingers** [comment]
Got a basic working version, though a quick question came up:

There's an error thrown for trying to get an instance variable from static methods, meaning that patching all methods would almost never work with the __instance parameter, or we remove the error and just set the instance variable to null if the method is a static method and the __instance variable is requested. Which would you prefer?

The working null __instance variable code looks like:


```
if (patchParam.Name == INSTANCE_PARAM)
	{
		if (!isInstance)
			Emitter.Emit(il, OpCodes.Ldnull);
		else if (patchParam.ParameterType.IsByRef)
			Emitter.Emit(il, OpCodes.Ldarga, 0); // probably won't work or will be useless
		else
			Emitter.Emit(il, OpCodes.Ldarg_0);
		continue;
	}
```

The last thing I want to add is the ability to allow something like:
[HarmonyPatchAll(BindingFlags.Public)]

Thoughts? Pull request should come in the next few days.

**Comment by pardeike** [comment]
A few reflections:

- null is fine and goes well with the Invoke() conventions users know

- make sure you reuse/extend existing routines for argument handling but I wait until a pr - pretty sure you do that already

- regarding the attribute: so far, the convention in Harmony was that it does not discriminate between public/private and I would love to continue to keep it that way. Adding a similar mechanic like TargetMethod (in plural though) would give special case users better control (i.e patching all getter)

**Comment by pardeike** [comment]
Added support for __originalMethod

**Comment by pardeike** [comment]
`[HarmonyPatchAll]` was implemented in https://github.com/pardeike/Harmony/commit/99f922fd1b4f42b7be7d8af0fc25cfa84a6f58b7#diff-b550cea7e6e2e41bdd319512ac1965e6. This completes this issue.
