### ISSUE TITLE
Is it possible to patch native libraries?

### ISSUE THREAD

**Issue by mnns** [pardeike/Harmony#459]
I'd like to patch MessageBox (a win32 dll)

    [DllImport("user32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    private static extern int MessageBox(IntPtr hWnd, string lpText, string lpCaption, uint uType);

I'm not sure if I can patch DllImport for example or otherwise.

Thanks

**Comment by pardeike** [comment]
Right now, native patches are restricted to full replacements. Once a method is patched, the original is destroyed by writing a jump instruction to the replacement. That makes patching native methods destructive and you can only write a transpiler that outputs the IL of your own code. Since the original is broken you cannot call the original from within your code and Harmony cannot either - thus Prefix/Postfix won't work.

**Comment by mnns** [comment]
> Right now, native patches are restricted to full replacements. Once a method is patched, the original is destroyed by writing a jump instruction to the replacement. That makes patching native methods destructive and you can only write a transpiler that outputs the IL of your own code. Since the original is broken you cannot call the original from within your code and Harmony cannot either - thus Prefix/Postfix won't work.

Thanks, is there a plan to fix this?

**Comment by pardeike** [comment]
This is very deep in the design of Harmony. If I would know how to do it I would implement it. At least one other solution does a very dirty switch on the bytes the jump is written but to me this looks very dangerous because it would not work in multithreaded scenarios.

**Comment by pardeike** [comment]
There seems to be a clever way to make this work. It requires some trickery so it's not trivial to implement. I will get to you when I have plenty of time to make it work correctly.

**Comment by pardeike** [comment]
More feedback from the MonoMod discord by DaNike seems to indicate that native methods share entrance points and it is therefore not safe to patch multiple native methods.

So for now this is a WONTFIX

**Comment by pardeike** [comment]
In https://github.com/pardeike/Harmony/tree/feature/monomod-core I am moving over to MonoMod.Core which means that we will get the chance to patch native methods in the future. I will remove the WONTFIX.

**Comment by krisrok** [comment]
Just referencing here MonoMod.Core is used: https://github.com/pardeike/Harmony/discussions/467#discussioncomment-6873403
The blocker now is an implementation in Harmony. Maybe the HarmonyX fork's implementation could be used as reference.

(@pardeike please don't get this wrong: This is no critique, I'm just trying to document the current state.)

**Comment by krisrok** [comment]
Oh well... at least from my limited testing it turns out it just works with the current version (https://github.com/pardeike/Harmony/commit/5c42611d90cb23fa6ddd2a78e086ccb838452d2c). 🤦‍♂️ 
Possibly since the switch to MonoMod?

Prefixed `MessageBox` like in @mnns's opening post:

Postfixed Unity3D's `UnityEngine.GameObject.SetActive()` which is defined as
```csharp
[MethodImpl(MethodImplOptions.InternalCall)]
[NativeMethod(Name = "SetSelfActive")]
public extern void SetActive(bool value);
```
(Editor-only, I did _not_ test this any further with a built project let alone IL2CPP)
