### ISSUE TITLE
Doc amendment: HarmonyPrepare

### ISSUE THREAD

**Issue by Vectorial1024** [pardeike/Harmony#464]
**Is your feature request related to a problem? Please describe.**
I spent many hours to (re)discover that, when I use `HarmonyPrepare`, I must use it together with `HarmonyTargetMethod`. If I use `HarmonyPrepare` but only uses `HarmonyPatch` to define what method to target, the patch is ineffective. The debug report from #463 helped me discover this. However, the current docs do not mention this fact:

https://harmony.pardeike.net/articles/patching-auxilary.html#prepare

**Describe the solution you'd like**
Perhaps place a warning at the doc that `HarmonyPrepare` must be used with `HarmonyTargetMethod`

**Describe alternatives you've considered**
(none; in my case I required `HarmonyPrepare`, so will have to also use `HarmonyTargetMethod`; magic function names for `HarmonyPrepare` etc should carry the same effect as the class attributes.)

**Additional context**
Or is this a bug? I am using CitiesHarmony, which is kind of a Cities Skylines derivative of Harmony.

Maybe you remember that chaotic time where Harmony had to negitiate with HugsLib when Harmony 2 was first launched in RimWorld. Coming back to Cities Skylines, Harmony 2 adoption was gradual, and it was after many bug reports that eventually someone came out and made CitiesHarmony, which is basically Harmony + redirection of old Harmony 1 to Harmony 2.

**Comment by pardeike** [comment]
Not true. If you add attributes to the class or to a prefix in it that define the target method you don’t need TargetMethod. Prepare will allow you to skip patching that method in any way you like (for example using a configuration state). 

TargetMethod is for specifying everything that attributes cannot due to their static data limitations. 

Prepare and Cleanup are general methods that are called from PatchClassProcessor. Think of them as before and after hooks just like in unit test frameworks with the addition of Prepare returning a bool can skip the patching to occur.
