### ISSUE TITLE
I call function from the instance inside lambda expression and it causes application to crash.

### ISSUE THREAD

**Issue by Rayyat** [pardeike/Harmony#494]
So I am modding a game and porting it to my own server, and i have added a messagelistener code like below;

        [HarmonyPatch(typeof(BaseLobbySceneController), "Start")]
        [HarmonyPostfix]
        public static void LobbyChat_Patch(BaseLobbySceneController __instance)
        {          
                lobbyConnection.OnMessage += delegate (object sender, PlayerIOClient.Message m)
                {
                    switch (m.Type)
                    {
                        case "chatMsg":
                            Console.WriteLine(m.GetString(1));
                             __instance.ChatBox.AddUserMessage(m.GetString(0), m.GetString(1),"user");
                            break;
                    }
                };
            
       
        
     

 The server works fine , i can see the messages sent/received in the BepInEx console but when the function  __instance.ChatBox.AddUserMessage(m.GetString(0), m.GetString(1),"user"); is called this causes the game to crash , is it because i am calling it from a lambda expression ? or is it a bug ?
 
 The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
 This is the message I get in the crash dumps.
 
 OS: Windows 10 x64
 .NET 4.8

**Comment by pardeike** [comment]
I think I’ve read that event handlers can only be called in instance methods and inside the class they belong to. They have some black magic attached to them. You are calling it from code outside the class and that violates this. 

I am not 100% sure but you better ask this in the discord server as GitHub isn’t the best way to discuss this and it excludes all the smart people that might know more. Since it’s a crashing bug I will keep this issue open so you can refer to it.

**Comment by Rayyat** [comment]
Is there a workaround I can do for this ? or it's just impossible ?

**Comment by pardeike** [comment]
Ask on the Discord!
