### ISSUE TITLE
Struct Data Overwrite

### ISSUE THREAD

**Issue by HideakiAtsuyo** [pardeike/Harmony#501]
Hello dear pardeike,

I want to overwrite the data of struct after a function execution, is it possible ?
Apparently can't be done(or I missed something) but I want to be sure.

Regards,
Hideaki.

**Comment by pardeike** [comment]
A struct is a value type. If you send or pass it somewhere you essentially make a copy of it (like a number for example). In order to change it you either pass it back if possible or you don’t pass the value type but only a reference to it using the keyword `ref`

In the future, please use the discord for support questions. Issues on GitHub are meant to report but in the product.
