### ISSUE TITLE
Integration with Unity

### ISSUE THREAD

**Issue by ENikS** [pardeike/Harmony#53]
It is not really an Issue...

I am considering modernization of [Unity.Interception](https://github.com/unitycontainer/interception) and looking at different libraries for technologies and inspirations. 

I was wondering if Harmony could be used for that purpose and if it has any advantages over other implementations?

**Comment by pardeike** [comment]
Is there more documentation on this interception project? I’m not sure I have the time to go through the source code to guess what it is actually doing. Maybe you can be more specific with your question.

**Comment by ENikS** [comment]
The documentation is available [here](https://msdn.microsoft.com/en-us/library/dn178466(v=pandp.30).aspx)

**Comment by pardeike** [comment]
Now I see. Harmony was mainly designed to decorate methods of a code base that was never made extensible in the first place. Microsofts Unity is a container that allows for decoration by design. 

It is a bit difficult to compare or combine both approaches since they have complete different scenarios in mind. Harmony can be applied at runtime and relies on manipulating jitted code which in specific cases and with read-only memory for jitted code can actually fail, especially in an enterprise scenario.

**Comment by ENikS** [comment]
I see. Thanks for the info.

**Comment by ENikS** [comment]
I really like the idea of changing behavior of methods without adding proxy type around the instance. 
How difficult would it be to create reliable mechanism to do it consistently?

**Comment by pardeike** [comment]
I think you should start your own project. What you want to do is out of the scope of this project and I think there are already libraries out there that do that on the dll level.

**Comment by ENikS** [comment]
Could you point me to these? I just recently started with these and still lucking necessary depth.

**Comment by pardeike** [comment]
Maybe something like https://stackoverflow.com/questions/5731857/how-to-patch-a-line-of-code-in-a-dll

Good luck
