### ISSUE TITLE
Class Transpiler

### ISSUE THREAD

**Issue by friuns2** [pardeike/Harmony#59]
i found Transpliter very usefull for functions but could you make it for class also? for example to change fields from private to public and etc...

**Comment by pardeike** [comment]
That is unfortunately not possible. Harmony only changes methods because that is what changing execution code does. There is no to me known way to alter the meta information or memory structure of classes during runtime.

Theoretically it would be possible but it probably would only for for a very specific runtime version and only for a very specific machine. And it would be way to much work and be enormously complex and one has to do this for all known version combinations out there. 

So it is practically impossible.
