### ISSUE TITLE
Could not load type 'CORINFO_METHOD_INFO' from assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

### ISSUE THREAD

**Issue by chinware** [pardeike/Harmony#616]
![image](https://github.com/pardeike/Harmony/assets/168338946/ac25100a-ee00-4574-8827-bbeed6d9ed4c)

.NET 8 windows 11 

The above error is reported when debugging rider, but everything is normal when running in rider。

**Comment by chinware** [comment]
**lib.harmony 2.3.3** has this problem, but **lib.harmony.thin** has no problem and everything works fine.

**Comment by nvirth** [comment]
Same issue here

**Comment by pardeike** [comment]
This earlier comment explains it: https://github.com/pardeike/Harmony/issues/616#issuecomment-2196199309

**Comment by nvirth** [comment]
So there is no fix? For some reason, the `.Thin` version does not work for me - there was an inexplicable build error if I changed to the `.Thin`, and also the docs says using the other version is the recommended way, so I rolled back to the normal version. But now I'm stuck :(

**Comment by pardeike** [comment]
The thin version is exactly what you need. It leave dependency management to you and the error, as described in this topic, is clearly hinting about it. You have a runtime dependency problem which needs to be solved by you, not Harmony. 

The reason this issue is closed is because Harmony does nothing wrong. If your dependencies conflict with the fat (normal) version it’s because it merges conveniently dependencies into one dll but that does not work for everyone. Therefore the thin version exists but leaves it up to the user to make sure the required types are available at runtime.
