### ISSUE TITLE
Compatibility with NugetForUnity

### ISSUE THREAD

**Issue by Edenlia** [pardeike/Harmony#623]
Unity Version: 2022.3.18f1

When I try to Download Harmony by NuGetForUnity. It only download backend `netstandard2.0` and no dll inside.
Then I mannully downloaded the nupkg from website and finally found out  `netstandard2.0` is not supported anymore, and `net472` works greatly in my Unity Version. 

But that spent me some hours to found out those things. I'm wondering if there any ways to directly download harmony by NuGetForUnity with correct backend lib or just provide some relevant prompts on FQA. I believe I am not the only one encountering this issue. I hope someone can help solve it so that others won't have to face the same problem in the future.

**Comment by pardeike** [comment]
You can try to use the thin version of Harmony but you need to include all dependencies yourself (or use transient dependencies). No idea what NugetForUnity is as I have never used it

**Comment by Edenlia** [comment]
Hi @pardeike  Thanks for the reply 

I found the cause of the issue. In Unity version 2022.3.18f1, the C# API compatibility by default uses .NET Standard 2.0, so package managers like NuGetForUnity will only download the DLLs targeting `netstandard2.0`. However, since Harmony no longer supports `netstandard2.0`, we need to manually download the DLLs for `net472`. I will reach out to the NuGetForUnity team to request compatibility with .NET Framework.

Thank you

**Comment by Aragas** [comment]
We support .NET Standard 2.0 for compilation purpose - it's a common API layer for different runtime versions like .NET Framework or .NET Core.

Restoring .NET Standard would be okay only for compiling purpose, but for running the game (runtime) the closes actual target framework should be used, if the package provides it

**Comment by Edenlia** [comment]
Sorry I'm not so familiar with C# target.

My understanding is that .NET Standard is an older, lower-level API standard. Compared to the API standards of .NET Framework or .NET Core, using .NET Standard to write C# dynamic libraries provides fewer features from the C# language. Therefore, Harmony did not directly support .NET Standard during development but instead implemented DLLs targeting specific versions of .NET Framework and .NET Core.

As for Unity, because Unity uses Mono as its backend, it ensures that .NET Standard DLLs can definitely run, but it does not guarantee that DLLs targeting .NET Framework or .NET Core will run properly. So, package management tools often take a safer approach by selecting .NET Standard DLLs. Now, if I use a DLL targeting something like .`net472` in my Unity project, althrough it work fine on my current platforms (Windows), but there's no guarantee it will be compatible with all other platforms.

Is that correct?

**Comment by Aragas** [comment]
> Sorry I'm not so familiar with C# target.
> 
> My understanding is that .NET Standard is an older, lower-level API standard. Compared to the API standards of .NET Framework or .NET Core, using .NET Standard to write C# dynamic libraries provides fewer features from the C# language. Therefore, Harmony did not directly support .NET Standard during development but instead implemented DLLs targeting specific versions of .NET Framework and .NET Core.
> 
> As for Unity, because Unity uses Mono as its backend, it ensures that .NET Standard DLLs can definitely run, but it does not guarantee that DLLs targeting .NET Framework or .NET Core will run properly. So, package management tools often take a safer approach by selecting .NET Standard DLLs. Now, if I use a DLL targeting something like .`net472` in my Unity project, althrough it work fine on my current platforms (Windows), but there's no guarantee it will be compatible with all other platforms.
> 
> Is that correct?

You're mostly correct about .NET Standard — it's an API abstraction, but it's not "runnable." You can't compile an executable that targets it directly; you must target either .NET Framework or .NET Core.

The idea is that if you know your actual runtime (like Framework for Mono), you should use that instead of the more generic .NET Standard library when resolving a NuGet package. For example, if you ship a NuGet package with both fx3.5 and netstandard2.0 libraries, and you're using the fx471 runtime, you can utilize the fx3.5 library. However, if you're using .NET 8 (net8.0), you'll need to rely on netstandard2.0 since there's no core-specific library available—fx3.5 is not compatible with net8.0, at least it's not guaranteed.

Mono serves as a replacement for .NET Framework, and common scenarios where a framework library won't function on Unix Mono are P/Invokes (invoking Windows DLLs), Windows Registry, and other COM-related APIs. In cases where a library requires Windows-specific functionality, Wine could be a potential workaround.

.NET Standard libraries can still use Windows APIs in many ways, this does not guarantee safety, so you can still run into issues.

Harmony does not support .NET Standard because it requires specific APIs that are only available on Framework or Core. Since .NET Standard lacks these APIs, a generic implementation isn't possible.

You might have a netstandard2.0 library that simply needs references to Harmony's APIs for compilation. In this scenario, the "bait and switch" technique is used: your library uses Harmony's netstandard2.0 ref library, but it expects that there will be an actual runtime specific library of Harmony available somehow with the executable.  
The executable project references Harmony's package. Since the executable will target either Framework or Core, the appropriate library will be distributed from there.  

The netstandard2.0 file should not be distributed, which is why it's located in the ref folder, not lib (taking about NuGet).
