### ISSUE TITLE
How to compile harmony ?

### ISSUE THREAD

**Issue by Chimrod** [pardeike/Harmony#630]
Hello,

I’m playing rimworld with the native linux version.

How can I compile the library and add it in the game ? Do you have any pointer explaining how to do ?

(this is only a documentation request)

**Comment by pardeike** [comment]
Does the official Harmony mod not work? https://github.com/pardeike/HarmonyRimWorld

The documentation for this project is only for core Harmony and will never include implementations.

**Comment by Chimrod** [comment]
The official mod only provide windows libraries (dll), and I haven’t found any package for linux. That’s why I’ve opened the issue here.

**Comment by pardeike** [comment]
Harmony mod works on macOS so I don’t see why it wouldn’t work on Linux. Anyway, wrong repo to report this as Harmony as it is works on Linux, macOS and Windows. It does however have no arm64 support yet and for that to happen you should report to the repository of MonoMod because Harmony relies on MonoMod.Common for low level patching.
