### ISSUE TITLE
Add support to .NET 9

### ISSUE THREAD

**Issue by jackdaniels980** [pardeike/Harmony#635]

**Comment by pardeike** [comment]
The low level dependency that Harmony uses just recently updated to NET9 but had one bug left that was just fixed a few days ago. I will keep this Issue open as a TODO for me to get started with the addition. 

One problem remains: the automatic tests in Harmony are kind of broken due to the introduction of Harmony Thin. I would feel more confident to have all tests execute correctly before I release NET9

**Comment by pardeike** [comment]
As mentioned earlier, NET9 support isn’t there yet. I have work to do after Harmony’s internal dependency just recently fixed the compatibility. Lots of personal stuff piling up for me right now but I get to it when I can.

**Comment by aaronportier** [comment]
Thank you so much for what you do. I was wondering if you believe what I am
seeing is a compatibility issue though for dot net 9 or is it something
else?

**Comment by pardeike** [comment]
Yes, it’s something that came up with net 9

**Comment by tyb-dev** [comment]
Probably related to [dotnet/runtime#93809](https://github.com/dotnet/runtime/pull/93809)

**Comment by pardeike** [comment]
Fixed by #637
