### ISSUE TITLE
Passing data to a patch method

### ISSUE THREAD

**Issue by wasabii** [pardeike/Harmony#74]
Since patch methods must be static, I'm finding it hard to pass data to them from the code doing the patching. Not seeing any existing feature, I'd recommend some magic variable like `__data` that can be sent into them from the `Patch` method.

Or maybe a way to simply set `__state` before calling the prefix.

**Comment by pardeike** [comment]
That would be nice. Unfortunately, this opens a whole can of worms when it comes to patching with multiple pitchers (like Mods that use Harmony independently). Since a patcher that comes after you would need to be able to call your methods again, all state need to 

- be serializable
- static/deterministic in its nature

The reason this principle was chosen is that each patcher just adds a modification to the chain and Harmony reruns the whole patch chain:

1st patcher:
Original -> P1 -> Result

2nd patcher:
Original -> P1 -> P2 -> Result

And so on. If you can come up with a hopefully simple way to make your idea work for the second patcher that needs to call the work unit P1 somehow, I’ll be glad to implement it.

**Comment by pardeike** [comment]
I’m closing this as patch methods are basically compile time and can therefore not have state. Harmony supports the patch factory pattern by using a DynamicMethod. Feel free to reopen this issue if necessary.
