### ISSUE TITLE
Patching methods marked as Internal Call

### ISSUE THREAD

**Issue by bbepis** [pardeike/Harmony#75]
Hi,
Is it possible to patch methods that are marked with the `MethodImplOptions.InternalCall` attribute?
For example, looking in the IL for UnityEngine.dll:
```cs
[GeneratedByOldBindingsGenerator]
[MethodImpl(MethodImplOptions.InternalCall)]
public static extern AssetBundle LoadFromFile(string path, [DefaultValue("0")] uint crc, [DefaultValue("0")] ulong offset);
```

These methods exist and can be tampered with, using Mono.Cecil. However, they cannot be hooked in Harmony as they have no method body.

I understand that attaching a transpiler would be not applicable in this case, but is it possible to add Prefix and Postfix patches to these methods? From what I've looked at in the source, the method patcher copies the IL from the original method to the old one. Would it be viable to then just call the original extern method since there is no IL to copy?

**Comment by pardeike** [comment]
I don’t know if the method table has an entry for those methods. The main problem here is the hook injection. Harmony usually adds a assembler jump into the trampoline or the real method code that points to the copy. Since there is no way to copy those, you cannot have the cake and eat it. You would need to provide the full content of the method with no way to call the (destroyed) original. And all that if those methods are in fact hookable.

**Comment by bbepis** [comment]
I'll take your word for it. Thanks for clarifying!

**Comment by metanqy** [comment]
I have the same issue, hope Harmony can support this situation.

**Comment by Lioncky** [comment]
> I have the same issue, hope Harmony can support this situation.

It directly link to cplusplus and no pointer could check in CSharp, a hard work
