### ISSUE TITLE
Deserialization exception

### ISSUE THREAD

**Issue by ivan-ra** [pardeike/Harmony#86]
Hi!
for me this code raises FileNotFoundException:
`harmony.Patch(original, new HarmonyMethod(prefix), null);`
`harmony.RemovePatch(original, HarmonyPatchType.Prefix); // FileNotFoundException`
But [this workaround](https://stackoverflow.com/questions/8564761/c-sharp-deserialization-of-system-type-throws-for-a-type-from-a-loaded-assembly) solves problem. Perhaps it's worth adding it to the library code

**Comment by pardeike** [comment]
Can you give me a stack trace? Not sure why you get such an exception and from where.

**Comment by ivan-ra** [comment]
this is stack trace: [stack.log](https://github.com/pardeike/Harmony/files/1998554/stack.log)
I have localized studio, so there are sometimes russian words in stack :)
It says cant find file with assembly (this file is in another directory, not where main program). And this is paradox: Harmony.HarmonyInstance.RemovePatch is called from this assembly.

**Comment by ivan-ra** [comment]
And when i add this strings in my code, all works fine
`public static class AssemblyResolverFix`
`{`
`    //Looks up the assembly in the set of currently loaded assemblies,`
`    //and returns it if the name matches. Else returns null.`
`    public static Assembly HandleAssemblyResolve(object sender, ResolveEventArgs args)`
`    {`
`        return Array.Find(AppDomain.CurrentDomain.GetAssemblies(), assembly => assembly.FullName == args.Name);`
`    }`
`}`
...
`AppDomain.CurrentDomain.AssemblyResolve += AssemblyResolverFix.HandleAssemblyResolve;`

**Comment by pardeike** [comment]
I've never heard about this workaround and so far I had nobody report it. Is this a corner case because of your runtime environment? I think as long as nobody else reports it I am a bit sceptical to add it as default in Harmony because it might break other things.

**Comment by pardeike** [comment]
I have a look and get back to you

**Comment by pardeike** [comment]
After looking at your example, I took a look at how RimWorld, the game that made Harmony big does it. I found this in the LoadAllMods code:
```csharp
if (!ModAssemblyHandler.globalResolverIsSet)
{
	ResolveEventHandler @object = (object obj, ResolveEventArgs args) => Assembly.GetExecutingAssembly();
	AppDomain currentDomain = AppDomain.CurrentDomain;
	currentDomain.AssemblyResolve += @object.Invoke;
	ModAssemblyHandler.globalResolverIsSet = true;
}
```
So I think it is necessary for the host application to define an assembly resolver if it deals with loaded dlls. But that code above was there before Harmony came. And I am pretty sure it's not Harmony's job to resolve assemblies.

Btw: unpatching in Harmony is almost like double-patching a method. Harmony does not restore the original assembler jump but instead creates a new dynamic method for every change to a method. And that includes unpatching or adding a second patch to the same method. Since this can happen across multiple assemblies, it uses serialization with no state to avoid complicated mapping. That is also the reason why patch methods mus be static.

I am going to close this issue as won't-fix because I think it's something that belongs to the application domain and not Harmony.
